export const ActionTypes = {
  GET_DATA_REQUEST: "GET_DATA_REQUEST",
  GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
  FILTER_BY_ARTIST: "FILTER_BY_ARTIST",
  SET_ALBUM: "SET_ALBUM",
  SET_SONG: "SET_SONG",
  PLAY_SONG: "PLAY_SONG"
};
